[package]
name = "mutate"
version = "0.1.0"
edition = "2018"
authors = ["Daniel P. Teberian"]
description = "Provides the mutate macro."
license = "Apache-2.0"
categories = ["no-std"]
repository = "https://github.com/LibertyOS-Development/mutate"
